[project]
name = "kitsune"
version = "0.1.0"
description = "AI agent microservice"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docker",
    "fastapi",
    "httpx",
    "logfire",
    "marimo",
    "pydantic-ai",
    "uvicorn[standard]",
]
